name: "ci"

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@main

      - name: Install pnpm
        uses: pnpm/action-setup@main
        with:
          version: 7

      - name: Set node version to 18
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: "pnpm"

      - name: Run install and build
        run: pnpm install && pnpm run build

      - name: Upload docs folder
        uses: actions/upload-artifact@main
        with:
          path: docs/

      - name: Deploy
        uses: actions/deploy-pages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
